name: "Ruby on Rails CI"
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_URL: "db/test.sqlite3"
      GITHUB_TOKEN: ${{ secrets.token }}
    steps:
      - name: Load rspec repo
        run: git clone https://username:$GITHUB_TOKEN@github.com/examinertest/testrspecs.git
      - name: Removing users specs
        run: rm -rf spec/
      - name: Moving spec folder
        run: mv testrspecs/spec .
      - name: Run tests
        run: bin/bundle exec rspec spec
